version: '3.6'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ../:/var/www/html:cached
      - ./nginx/conf.d:/etc/nginx/conf.d/:cached
      - ./nginx/localhost.crt:/etc/ssl/localhost.crt:cached
      - ./nginx/localhost.key:/etc/ssl/localhost.key:cached
    networks:
      - net
    ports:
      - "80:80"
      - "443:443"
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../:/var/www/html:cached
    networks:
      - net
networks:
  net:
    driver: "bridge"
volumes:
  applications:
    driver: "local"
